name: taprium_upscale_runner
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.3

# Add regular dependencies here.
dependencies:
  envied: ^1.3.2
  get_it: ^9.2.0
  hive: ^2.2.3
  http: ^1.6.0
  logger: ^2.6.2
  path: ^1.9.0
  pocketbase: ^0.23.0+1

dev_dependencies:
  build_runner: ^2.10.4
  envied_generator: ^1.3.2
  lints: ^6.0.0
  test: ^1.25.6
