name: Multi-Arch Docker Build and Push
on: ["push"]
permissions:
  packages: write
  contents: write


jobs:
  build_multi_arch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Set up QEMU for emulation (allows building ARM on an AMD64 runner)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 2. Set up Docker Buildx (the multi-arch builder)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      # 3. Log in to your container registry (e.g., Docker Hub)
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/taprium/upscale-runner
          tags: |
            # Always produce a nightly tag
            type=raw,value=nightly
            # Produce 'master' tag only when a git tag is pushed
            type=raw,value=master,enable=${{ startsWith(github.ref, 'refs/tags/') }}

      # 4. Build, push, and create the manifest list for all platforms
      - name: Build and Push Multi-Arch Image
        uses: docker/build-push-action@v5
        with:
          context: . 
          push: true
          # The single tag that will contain the manifest list
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
          # Specify all desired architectures
          platforms: linux/amd64,linux/arm64
